name: Rust

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain'
      - '.github/workflows/rust.yml'

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.2.0

      - name: clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
